repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        stages: [pre-commit]

-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
        stages: [pre-commit]

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        stages: [pre-commit]

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow

# Temporarily removing mypy due to Python 3.12 compatibility issues
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.7.1
#     hooks:
#     -   id: mypy