[tool.black]
line-length = 88
extend-exclude = '''
(
    venv
    | .venv
    | __pycache__
    | 85F_5th_backup
    | 85F_5th_revised
    | output
    | spreadsheets
    | dist
    | backups
    | .vscode
    | test_db
    | database
)
'''

[tool.isort]
profile = "black"  # Makes isort compatible with black
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 2  # Changed from 0 to 2
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
skip = [
    "venv",
    ".venv",
    "__pycache__",
    "85F_5th_backup",
    "85F_5th_revised",
    "output",
    "spreadsheets",
    "dist",
    "backups",
    ".vscode",
    "test_db",
    "database"
]